version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - ./repository/postgresql/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  web:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres