services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/storage/postgresql/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - bot_network

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass "suWD2AlYlVCUoNCz"
    ports:
      - "6379:6379"
    networks:
      - bot_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      - postgres
      - redis
    networks:
      - bot_network

volumes:
  postgres_data:

networks:
  bot_network: