bot:
  token: 7917010015:AAFgCxFiaqo6h0LVNdbRyAcVXShPz2gDebo

postgres:
  host: postgres
  port: 5432
  db_name: postgres
  user_name: postgres
  pwd: postgres
timeout: 10s
migration: file://././internal/storage/postgresql/migrations
redis:
  host: redis
  port: 6379
  pwd: suWD2AlYlVCUoNCz
